Fix 'schema_file_type' method instead of 'schema_file'
```
NoMethodError: undefined method `schema_file' for primary:Module

      default_schema = ENV['SCHEMA'] || ActiveRecord::Tasks::DatabaseTasks.schema_file(ActiveRecord::Base.schema_format)
                                                                          ^^^^^^^^^^^^
Did you mean?  schema_file_type
```